### PR TITLE
Initial commit of summarizer

### PR DESCRIPTION
**Pull request by rcedgar**
Ready to go. Here, the reverse happened from last time: I tried to commit directly to the repo thinking it was zero risk because I'm adding a new source directory, but I accidentally did the right(?) thing. Still not getting git...

### CODE REVIEW

**Comment by ababaian** [comment]
Will this be compatible with `python3`, `python2` is deprecated and we don't have it installed in the cluster currently.

**Comment by rcedgar** [comment]
Updated to python3.

**Comment by ababaian** [comment]
Hey @rcedgar,

The accession files `s3://serratus-public/var/acc_len_taxid.txt` and `s3://serratus-public/var/taxid_desc.txt` are not in the S3 bucket. There is a file called `s3://serratus-public/var` which is probably one of the two accession files above.

**Comment by rcedgar** [comment]
Fixed the S3 bucket.

**Comment by ababaian** [comment]
And do you have the associated scripts/commands for parsing the genbank file into these two files? That should either go in the README or if it's more involved be it's own script.

**Comment by ababaian** [comment]
The summarizer potentially 
does not deal well with empty records. I will test again right now with another file to confirm if that was the issue.

```
bash-4.2# aws s3 cp s3://serratus-public/out/200423_ab_cov2r/bam/SRR9658394.bam ./
download: s3://serratus-public/out/200423_ab_cov2r/bam/SRR9658394.bam to ./SRR9658394.bam
bash-4.2# samtools view SRR9658394.bam > SRR9658394.sam 
bash-4.2# ls -alh SRR9658394.sam 
-rw-r--r-- 1 root root 0 Apr 25 22:54 SRR9658394.sam
bash-4.2# python3 serratus_summarizer.py SRR9658394.sam summary.txt -
Traceback (most recent call last):
  File "serratus_summarizer.py", line 185, in <module>
    Order = GetOrder(AccToHits)
  File "serratus_summarizer.py", line 65, in GetOrder
    Order.sort(key=CmpKey__)
AttributeError: 'range' object has no attribute 'sort'
```

**Comment by rcedgar** [comment]
Yes, and happy to provide, but the metadata files should be stable as long as we focus on Cov. Can I defer to a later pull? As with posting a bvfilter repo, this would be a fair amount of work and (1) don't want to delay a production run + (2) easier for me to do quick hacks and fixes my own way until we're reasonably sure these will be included in the production pipeline. I'm in major cognitive overload here doing several Cov-related projects in parallel.

**Comment by rcedgar** [comment]
`'range' object has no attribute `'sort``

you would get that error if you want the old python2 script under python3, do you see python3 in the shebang at the top of the source?

**Comment by ababaian** [comment]
```
#!/usr/bin/python3

from __future__ import print_function
import sys
import os

COV_BINS = 16

InputFileName = sys.argv[1]
SummaryFileName = sys.argv[2]
```

**Comment by ababaian** [comment]
Can confirm, it will run under `python2`

**Comment by rcedgar** [comment]
Arrgh, I'm a git-idiot. I committed the correct version this time, I think...

**Comment by rcedgar** [comment]
For those of you not raised in Yorkshire in the 1960s, "git" was there used as term of abuse indicating general lack of competence:

[Wikipedia article on git](https://en.wikipedia.org/wiki/Git_(slang))

**Comment by ababaian** [comment]
That's `apt` because you git makes all it's users feel like gits. It gets better but not really.

**Comment by rcedgar** [comment]
Right, I've been doing the same for years, except I've been using subversion which has a quite different conceptual model.

**Comment by ababaian** [comment]
OK, she's in production :rocket:!

**Pull request merged**
